### ISSUE TITLE
Install.php needs to find the system/language and system/core folders

### ISSUE THREAD

**Issue by imtiazmahbub** [btiteam/xbtit#10]
In install.php, All instances of 'include/' replaced with 'system/core/' 
and
'language/' replaced with 'system/' 

Also find and replace some /access_code and /cache with /system prefixed
fixes this issue

**Comment by Gh0st4unt3r** [comment]
This will be worked on thank you for bringing this to our attention.

**Comment by HDVinnie** [comment]
fixed
