### ISSUE TITLE
Comment on torrents don't work on XBTIT 2.5.1

### ISSUE THREAD

**Issue by Enoch-X** [btiteam/xbtit#11]
Hi there,

First of all thanks for this great script. I've tested many torrent scripts and to my opinion XBTIT is by far the best in Torrent land!
I've upgraded from XBTIT 2.3.0 to version 2.5.1. Everything works fine except the comment system don't display the comments on  the torrent files. The preview works fine but when I try to confirm to place the comment, the comment is not being placed and stays empty.

I've been throug all the configuration settings and can't find a reason why the comments are not being displayed. I also checked the MySQL database and the comments are being written correctly to the DBase in the field xxxx_comments.

I've been through many .php and .tpl files of the script to see if I could find a clou. What I see in the file /style/xbtit_default/torrents.list.tpl on line 82 is that there might be a typo that can cause the error but I'm not sure!

`<td align="center" width="30" class="lista" style="text-align: center;"><tag:torrents[].coments /></td>`

Shouldn't the word "**coments**" be written as "**comments**"? But then again I've chanched this too from coments to comments and tried to see if it is the solution, even emptied my browser cache but it didn't work, the problem still exist.

Can someone please help me out? I'm stuck and don't know what to do to find an answer or solution.

Your help would be highly appreciated.

Thanks in advance!

**Comment by Enoch-X** [comment]
TnX for your time Gh0st4unt3r ...

**Comment by Gh0st4unt3r** [comment]
I have checked from a code point and all seems ok, You are right they are being recorded ok in the database.

this could either be a design problem or a code confliction somewhere with the old tpl tag system that was used on bTemplate, I have assigned 2 other developers that could probably assist me in solving this.

**Comment by Enoch-X** [comment]
Hi Alan,

thanks for your message, and thanks for your time and energy too!

I hope we can solve this issue a.s.a.p. so that we can get the script 
stable.

I keep looking for the answer, if I find it I'll share it with you.

Good Luck,

Stay in touch!

Greetings!

**Comment by q8-hma** [comment]
Hello

update comment.php
find
`  do_sqlquery("INSERT INTO {$TABLE_PREFIX}comments (added,text,ori_text,user,info_hash) VALUES (NOW(),\"$comment\",\"$comment\",\"$user\",\"" . mysqli_query($GLOBALS['conn'],StripSlashes($_POST["info_hash"])) . "\")",true);`

replace with
`  do_sqlquery("INSERT INTO {$TABLE_PREFIX}comments (added,text,ori_text,user,info_hash) VALUES (NOW(),\"$comment\",\"$comment\",\"$user\",\"" . mysqli_real_escape_string($GLOBALS['conn'],StripSlashes($_POST["info_hash"])) . "\")",true);`

update torrents.list.tpl
find
`          <td align="center" width="30" class="lista" style="text-align: center;"><tag:torrents[].coments /></td>`
replace with
`          <td align="center" width="30" class="lista" style="text-align: center;"><tag:torrents[].comments /></td>`

try it and see

the main problem is the comments not have info_hash data

**Comment by Enoch-X** [comment]
Problem Solved, it works like a charm! Thank you very much **q8-hma**, you found the answer and solution! Thank you for sharing it with us! God Bless You!

**Comment by Gh0st4unt3r** [comment]
Great work q8-hma, will get this added onto the branch files,  you are also free to make contributions to the code also submit/push them to the XBTIT github too.

**Comment by Enoch-X** [comment]
Yeah q8-hma did it, great job,.. well done!

**Comment by q8-hma** [comment]
Hello
Enoch-X : good to know its work fine

Gh0st4unt3r : I will all my best ,,, but I'm sorry because my english it's not that good

**Comment by Enoch-X** [comment]
Thanks HAMAD ADHBIYAH, for sharing this solution with us, we really 
appreciate it!

And eh, I understand you perfectly, your English is good enough.

You're the man!

**Comment by q8-hma** [comment]
ur welcome if u fine any bug

report about it and we will fix it

thnx

**Comment by Enoch-X** [comment]
A Million TnX for your help!

Stay in touch!

God Bless!

Bye Bye!
