### ISSUE TITLE
Some bugs - v2.5.1

### ISSUE THREAD

**Issue by scriptzteam** [btiteam/xbtit#12]
Torrent download not works even the torrent file is in torrent folder and folder set to 777

Comments not works

**Comment by scriptzteam** [comment]
Oh and also there **banip** on url index.php?page=admin&user=2&code=***&do=banip&action=read

MySQL query error!


Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '}bannedip b LEFT JOIN {$TABLE_PREFIX}users u ON u.id=b.addedby ORDER BY b.added ' at line 1
Query: SELECT b.*, u.username FROM {$TABLE_PREFIX}bannedip b LEFT JOIN {$TABLE_PREFIX}users u ON u.id=b.addedby ORDER BY b.added DESC

**Comment by scriptzteam** [comment]
connect to seeder not works even i can see them on site

**Comment by Gh0st4unt3r** [comment]
This has now been resolved it was a typo error on the quotations if you get a copy of the admin.banip.php from the XBTIT-2-DEV in the admin folder and upload it to your server.

this should resolve your issue now.

thank you for your imput
