### ISSUE TITLE
Install bug - v3.0

### ISSUE THREAD

**Issue by scriptzteam** [btiteam/xbtit#13]
In install.php you should update the path for settings.php ;)

/system/core/settings.php

Either it will show mysql error on index.php

//Btw 3.0 is broken, no index :D

**Comment by KingCobra58** [comment]
There is no xbtit v3.0 yet only v 2.5.1

**Comment by scriptzteam** [comment]
Ermmmmm https://github.com/btiteam/xbtit/commit/ab128fd999496748e22b4cbc6d8f776e8e53cfe4

**Comment by Gh0st4unt3r** [comment]
There is a version 3 on the master, this is for development and testing, not for live production websites, we do advise the master edition on the github branch may be likley to be unstable so all issues are noted and worked on.

Sorry KingCobra i forgot to inform you.

**Comment by HDVinnie** [comment]
fixed
