### ISSUE TITLE
Few bugs in 2.5.1

### ISSUE THREAD

**Issue by newbiee12** [btiteam/xbtit#15]
First of all, thank you for the new version.

I've just installed the 2.5.1 version on my server to test it and here are the few bugs that I've found:

- Admin's email from the installation did not import into the tracker's settings.

- In the PHP error log section, when I tried typing the logs name, line amount or the logs path, nothing was visible/saved. The cursor was moving on, but no text was visible.

- It's the same issue I had with the 2.4 version in the admin section

Current version: http 1.1 409 conflict date: thu, 16 jun 2016 14:46:00 gmt content-type: text html; charset=utf-8 connection: close set-cookie: __cfduid=dd0f743792bded16a4741cc5992cd5a601466088360; expires=fri, 16-jun-17 14:46:00 gmt; path= ; domain=.google.com; httponly cache-control: max-age=6 expires: thu, 16 jun 2016 14:46:06 gmt x-frame-options: sameorigin server: cloudflare-nginx cf-ray: 2b3f0c7df5401fa6-dfw

- There may be a displacement in the columns Speed and Av. as shown in the screenshot
http://imgur.com/2I0aKbz

- If popup window for torrents is enabled, upong clicking show/hide files, the window content scrolls down; you need to scroll up to see the files

- It might be a minor issue, but the install.txt file contains reference to the 757 revision
https://btit-tracker.svn.sourceforge.net/svnroot/btit-tracker/BtitT2/branches/beta
Does it need to be updated?

I will post more issues if I find any.

Thanks.

**Comment by Gh0st4unt3r** [comment]
We will test this and hopefully come up with a resolution soon and update for the next version 2.5.2 or 2.5.3

**Comment by Gh0st4unt3r** [comment]
Update:
Some of the errors have been fixed we will be working on some of the minor ones and will be checking on the php logs to ensure this works very soon too.

**Comment by q8-hma** [comment]
Hello

you can fix error log path and name by this steps

open admin.php_errors_log.php

find
`(isset($_POST["php_log_path"]) && !empty($_POST["php_log_path"])) ? $log_settings["php_log_path"]=mysqli_query($GLOBALS['conn'],str_replace("\\", "/", $_POST["php_log_path"])) : $log_settings["php_log_path"]="";`
replace
`(isset($_POST["php_log_path"]) && !empty($_POST["php_log_path"])) ? $log_settings["php_log_path"]= mysqli_real_escape_string($GLOBALS['conn'],str_replace("\\", "/", $_POST["php_log_path"])) : $log_settings["php_log_path"]="";`

find
`$log_settings["php_log_name"]=isset($_POST["php_log_name"])?mysqli_query($GLOBALS['conn'],htmlentities($_POST["php_log_name"])):$log_settings["php_log_name"]="";`
replace
`$log_settings["php_log_name"]=isset($_POST["php_log_name"])?mysqli_real_escape_string($GLOBALS['conn'],htmlentities($_POST["php_log_name"])):$log_settings["php_log_name"]="";`

find
`$log_settings["php_log_lines"]=isset($_POST["php_log_lines"])?mysqli_query($GLOBALS['conn'],((int)0+$_POST["php_log_lines"])):$log_settings["php_log_lines"]="";`
replace
`$log_settings["php_log_lines"]=isset($_POST["php_log_lines"])?mysqli_real_escape_string($GLOBALS['conn'],((int)0+$_POST["php_log_lines"])):$log_settings["php_log_lines"]="";`


this will fix save error log path, try it and let me know

and install.php was fix to update tracker email,announce url,XBT announce url and log path automatically

**Comment by Gh0st4unt3r** [comment]
Has all the issues noted in this been fixed, please confirm and
