### ISSUE TITLE
Admin user now registered and failed registrations 2.5.1

### ISSUE THREAD

**Issue by hireshi** [btiteam/xbtit#25]
I tried to delete and upload fresh several times into a new database.

I create an Admin during the installer (e.g admin pass: 1234567)

When I go on to sign in, "no such user exists"..

If I try to register a new user, I am greeted with the following message after I tap "Confirm":

MYSQL QUERY ERROR:
Error: Field 'warnreason' doesn't have a default value
Query: INSERT INTO `xbtit_users` (`username`, `password`, `salt`, `pass_type`, `dupe_hash`, `random`, `id_level`, `email`, `style`, `language`, `flag`, `joined`, `lastconnect`, `pid`, `time_offset`, `torrentsperpage`) VALUES ('adgagfafgafgd', '03a2124b9939ac16c3de9b46aa529300', '', '1', 'b9868d5a44c1bf67b993', 410909, 2, 'emailhere@hotmail.com', 1, 1, 11, NOW(), NOW(),'a7c5204fd9ef20548b510b5867f93d69', '-6', 15)

**Comment by Gh0st4unt3r** [comment]
I have updated a few things in the install.php file feel free to test this from the  XBTIT-2-DEV branch if you are using this version.

let me know if any of this resolves your issue.
