### ISSUE TITLE
gethostbyaddr(): Address is not a valid IPv4 or IPv6 address

### ISSUE THREAD

**Issue by CaPaCuL** [btiteam/xbtit#26]
[:error] [pid 6643] [client 1.*.*.*:53796] PHP Warning:  gethostbyaddr(): Address is not a valid IPv4 or IPv6 address in /var/www/virtual/tracker/announce.php on line 399
--------------------------------
[:error] [pid 1648] [client 2.*.*.*:42644] PHP Warning:  gethostbyaddr(): Address is not a valid IPv4 or IPv6 address in /var/www/virtual/tracker/announce.php on line 399

Seeds aren't be able to connect on tracker (2.5.1).
client 1.*.*.*: seed
client 2.*.*.*: leecher

**Comment by Gh0st4unt3r** [comment]
Will have a look into this, thank you for the information, could you also let me know what server you are running (OS - PHP version, Mysql version etc)

**Comment by CaPaCuL** [comment]
OS: CentOS 7.2.1511 (x86_64)
PHP Version: 5.4.16 (cli) (built: Aug 11 2016 21:24:59)
MySQL Version: 15.1 Distrib 5.5.50-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by Gh0st4unt3r** [comment]
Thank you, also have you tried to click update in the torrent details

see attached image 
http://screencast.com/t/vJRtVBbp

**Comment by Gh0st4unt3r** [comment]
I have made a change to the announce.php feel free to grab this from the XBTIT-2-DEV

let me know if this resolves the issue.

**Comment by CaPaCuL** [comment]
What do you mean XBTIT-2-DEV? Is it https://github.com/btiteam/xbtit/archive/master.zip ?

**Comment by Gh0st4unt3r** [comment]
the master is new developments which is not suitable for live enviroments

here is the XBTIT 2 - https://github.com/btiteam/xbtit/archive/XBTIT-2-DEV.zip   the updated files will be in this one

**Comment by CaPaCuL** [comment]
Nothing has changed.

[Tue Aug 16 23:22:33.229815 2016] [:error] [pid 1364] [client 1.2.3.4:58424] PHP Warning:  gethostbyaddr(): Address is not a valid IPv4 or IPv6 address in /var/www/virtual/tracker/announce.php on line 399
[Tue Aug 16 23:30:48.787001 2016] [:error] [pid 15233] [client 1.2.3.5:57602] PHP Warning:  gethostbyaddr(): Address is not a valid IPv4 or IPv6 address in /var/www/virtual/tracker/announce.php on line 399

client 1.2.3.4: seed
client 1.2.3.5: leecher

XBTIT: XBTIT-2-DEV
OS: CentOS 7.2.1511 (x86_64)
PHP Version: 5.4.16 (cli) (built: Aug 11 2016 21:24:59)
MySQL Version: 15.1 Distrib 5.5.50-MariaDB, for Linux (x86_64) using readline 5.1

Is there any OS or php/mysql version you suggest?

**Comment by q8-hma** [comment]
Hello

open "announce.php"

find
`    $ip =  mysqli_query($GLOBALS['conn'],$ip);`
replace with
`    $ip =  mysqli_real_escape_string($GLOBALS['conn'],$ip);`

find
`     $agent =  mysqli_query($GLOBALS['conn'],$_SERVER["HTTP_USER_AGENT"]);`
replace with
`     $agent =  mysqli_real_escape_string($GLOBALS['conn'],$_SERVER["HTTP_USER_AGENT"]);`

find
`$remotedns =  mysqli_query($GLOBALS['conn'],$tldm[2]);`
replace with
` $remotedns =  mysqli_real_escape_string($GLOBALS['conn'],$tldm[2]);`

let me know if any of this resolves your issue.

**Comment by CaPaCuL** [comment]
I remove old installations and I downloaded+installed XBTIT-2-DEV.zip again.
Changes have already been made. Just like:

`$ip =  mysqli_real_escape_string($GLOBALS['conn'],$ip);`
`$agent =  mysqli_real_escape_string($GLOBALS['conn'],$_SERVER["HTTP_USER_AGENT"]);`
`$remotedns =  mysqli_real_escape_string($GLOBALS['conn'],$tldm[2]);`

It does not give an error, seeding/leeching is working correctly now. Thanks so much.
