### ISSUE TITLE
www.btiteam.org's registering system is not working

### ISSUE THREAD

**Issue by CaPaCuL** [btiteam/xbtit#27]
www.btiteam.org's registering system is not working.

I can not get the activation mail. And I can not get re-activation mail. Inbox & Junk box are empty

**Comment by Gh0st4unt3r** [comment]
Will look at your registration information and confirm you.

**Comment by CaPaCuL** [comment]
thx my username is CaPaCuL

**Comment by Gh0st4unt3r** [comment]
I have activated your account for you.

**Comment by CaPaCuL** [comment]
thanks so much
