### ISSUE TITLE
SMTP+HTTP 500 Error for v2.5.1

### ISSUE THREAD

**Issue by CaPaCuL** [btiteam/xbtit#28]
I changed the SMTP at "Admin Access"->"Tracker's Setings"->"Tracker's Setings"->"Mail Type".

When the new user tries to be registration:
The new user receives a HTTP 500 Error and he can not receive activation mail.
httpd error log:
`......... PHP Fatal error:  Class 'SMTP' not found in ..../tracker/phpmailer/class.phpmailer.php on line 1444, referer: http://tracker.domain.tld/index.php?page=signup`

--------
I researched a little the phpmailer mistakes and I changed related lines at class.phpmailer.php file as follows:

_________
search:
-----------------
    public function getSMTPInstance()
    {
        if (!is_object($this->smtp)) {
            $this->smtp = new SMTP;
        }
        return $this->smtp;
    }
-----------------
_________
replace:
-----------------
    public function getSMTPInstance()
    {
        if (!is_object($this->smtp)) {
          require_once( 'class.smtp.php' );
            $this->smtp = new SMTP;
        }
        return $this->smtp;
    }
-----------------

And mails come now.

I'm expecting to make related changes to the new version.

**Comment by flier56** [comment]
may want to also leave a commit here about this
https://github.com/PHPMailer/PHPMailer

**Comment by q8-hma** [comment]
thnx we will fix it now
