### ISSUE TITLE
Last IP doesn't seem at new member profile for v2.5.1

### ISSUE THREAD

**Issue by CaPaCuL** [btiteam/xbtit#29]
Last IP doesn't seem at new member profile for v2.5.1.
But it seems as 0.0.0.0 at administrator account (created during the installation step).

There is an obvious error in the two conditions. Can you solve this issue?

**Comment by q8-hma** [comment]
try this one

open index.php

find 
`session_name("xbtit");`

add below
`session_start();`


let me now if it fix it or no

thnx for the report

**Comment by CaPaCuL** [comment]
Yes, this solution is working as tolerable. Last IP does seem. But not after logout. It's working after closing the browser.

**Comment by q8-hma** [comment]
OK try this one 

open include/functions.php

go to function check_online

find 
```php
@quickQuery("UPDATE {$TABLE_PREFIX}online SET session_id='$session_id', user_name=$uname, user_group=$ugroup, prefixcolor=$prefix, suffixcolor=$suffix, location=$location, user_id=$uid, lastaction=UNIX_TIMESTAMP() $where");
```
replace with
```php
@quickQuery("UPDATE {$TABLE_PREFIX}online SET session_id='$session_id', user_name=$uname, user_group=$ugroup, prefixcolor=$prefix, suffixcolor=$suffix, location=$location, user_id=$uid, lastaction=UNIX_TIMESTAMP(), user_ip='$ip' $where");
```

find
```php
@quickQuery("UPDATE {$TABLE_PREFIX}users SET lastconnect=NOW() WHERE id=$uid AND id>1");
```
replace with
```php
@quickQuery("UPDATE {$TABLE_PREFIX}users SET lastconnect=NOW(), cip='$ip' WHERE id=$uid AND id>1");
```

this will update the ip on online database and will update ip on user database if not find user on online database

let me now if it fix it or no

**Comment by CaPaCuL** [comment]
Yes, it fixed. Thanks so much.
