### ISSUE TITLE
Notice:  Undefined index

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#3]
[12-Apr-2016 11:40:46 America/New_York] PHP Notice:  Undefined index: infos in /home/public/www/html/xbtitgithub/admin/admin.main.php on line 163

**Comment by Gh0st4unt3r** [comment]
Updated and should now be on the latest Github submission

**Comment by flier56** [comment]
that error looks to be fixed now seeing this error when i clear out php error log
[12-Apr-2016 13:45:03 America/New_York] PHP Warning:  fread(): Length parameter must be greater than 0 in /home/public/www/html/xbtitgithub/admin/admin.php_errors_log.php on line 89

**Comment by Gh0st4unt3r** [comment]
On the latest submit has that solved the error,

**Comment by flier56** [comment]
still getting this error when error log is cleared
[12-Apr-2016 13:45:03 America/New_York] PHP Warning: fread(): Length parameter must be greater than 0 in /home/public/www/html/xbtitgithub/admin/admin.php_errors_log.php on line 89

**Comment by Gh0st4unt3r** [comment]
ok will look further into it, thank you for getting back to us.

**Comment by Gh0st4unt3r** [comment]
let me know how you get on with that update.

**Comment by flier56** [comment]
opens to blank page
[12-Apr-2016 15:00:14 America/New_York] PHP Fatal error:  Cannot redeclare in() (previously declared in /home/public/www/html/xbtitgithub/admin/admin.php_errors_log.php:40) in /home/public/www/html/xbtitgithub/admin/admin.php_errors_log.php on line 195

**Comment by Gh0st4unt3r** [comment]
Ok i have added another solution to github,  put a filesize check in hopefully it will put up that no action if empty and process the clean log if has content.

**Comment by flier56** [comment]
that loads to a white page that says The file is empty like you open a new blank window

**Comment by Gh0st4unt3r** [comment]
Ok i have checked and reverted code, can you check to ensure the folders and files would be writable where the log location will be,  i think if there is no log and size is 0 it would be able to delete nothing.

can you also let me know what PHP version and operating system you are running so i can try replicate this error.

**Comment by flier56** [comment]
PHP version 5.6.11-1ubuntu3.1
ubuntu 15.10 64 bit server running in virtualbox
files and folders are all writable this happens if i manually delete all the error logs from the error log file
and it is a blank file. this does not happen in older version of xbtit

**Comment by Gh0st4unt3r** [comment]
I will get this checked and investigate this further, thank you for bringing it to my attention will hopefully have a resolution to this error, i will see if i can replicate and reproduce what you are seeing.
so far the tests are currently run on php 5.6.20 and 5.7

**Comment by flier56** [comment]
found a work around to fix the blank page error i went into xbtit_settings in database
php_log_name and added a space after xbtit-errors now the page will open when blank

**Comment by flier56** [comment]
if i delete the file from the folder i do not see this error so i think the work around is to delete the file and not leave a empty file in the error folder

**Comment by Gh0st4unt3r** [comment]
Noted. untill i get a fix that will handle the files properly.
