### ISSUE TITLE
Torrent's Peers Page "No Peers" Trouble for version XBTIT-2-DEV

### ISSUE THREAD

**Issue by CaPaCuL** [btiteam/xbtit#32]
When I click to torrent's seeder or leecher at torrent details page, I see "No Peers" text. However, there are seeders+leechers for torrent.

http://mytracker.domain.tld/index.php?page=peers&id=32a7b7798998e048d82505330c3e506e726563a2
No peers

**Comment by q8-hma** [comment]
Hello

what ver u install ??

**Comment by CaPaCuL** [comment]
version 2.5.2 but I installed from https://github.com/btiteam/xbtit/archive/XBTIT-2-DEV.zip at Aug 23 2016.

**Comment by CaPaCuL** [comment]
When used in this case is going xbt backend activated.
if xbtt is deactivated, it's worked. But old torrents are seen as seederless+leecherless=peerless.

**Comment by CaPaCuL** [comment]
When I created new torrent file with multiple trackers (1-.../announce.php 2- ...:2710/announce) and when I activating xbtt, 2nd tracker (:2710/announce) give me "unregistered torrent pass" error. Later 1st tracker too.

Is there a bug in the codes?
Or am I doing something wrong?

**Comment by q8-hma** [comment]
Hello

u can't mix xbt and php ,u need to active only one

i can make php file to move from php to xbt

**Comment by CaPaCuL** [comment]
PHP or XBTT.. Which do you recommend?

**Comment by q8-hma** [comment]
i recommend xbt is better

this code to move the from php to xbt

this code for torrents
```php
<?
$THIS_BASEPATH=realpath(dirname(__FILE__));
define("IN_BTIT",true);
include($THIS_BASEPATH."/btemplate/bTemplate.php");
require($THIS_BASEPATH."/include/functions.php");
session_name("xbtit");
session_start();
dbconn(true);
$query = "SELECT info_hash as hash, UNIX_TIMESTAMP(data) as added FROM {$TABLE_PREFIX}files";
$results = get_result($query,true,$btit_settings['cache_duration']);
foreach ($results as $tid=>$data) {
$to=do_sqlquery("INSERT INTO xbt_files SET info_hash=0x".$data['hash'].", ctime=UNIX_TIMESTAMP() ON DUPLICATE KEY UPDATE flags=0",true);
if($to)
echo ($data['hash']." :Saved ....<br>");
}
?>
```


this code for users
```php
<?
$THIS_BASEPATH=realpath(dirname(__FILE__));
define("IN_BTIT",true);
include($THIS_BASEPATH."/btemplate/bTemplate.php");
require($THIS_BASEPATH."/include/functions.php");
session_name("xbtit");
session_start();
dbconn(true);
$query="select id,pid FROM {$TABLE_PREFIX}users WHERE id>1";
$results=get_result($query,true,$btit_settings['cache_duration']);
foreach ($results as $tid=>$data) {
$ur=do_sqlquery("INSERT INTO xbt_users (uid, torrent_pass) VALUES (".$data['id'].",'".$data['id']."') ON DUPLICATE KEY UPDATE torrent_pass='".$data['id']."'",true);
if($ur)
echo ($data['id']." :Saved ....<br>");
}?>
```

**Comment by q8-hma** [comment]
the file need to be on the main tracker folder

**Comment by CaPaCuL** [comment]
Ok. thanks so much. But what should be the file names and permissions? Or Are these files to run only once?

**Comment by q8-hma** [comment]
ur welcome
np about the name and permissions like (xbt2php.php) permisstions 755 
only one time after that delete the file

but if u change it to php and after to xbt need to do it again
