### ISSUE TITLE
Comments still dont work in version 2.5.3, fixed it myself

### ISSUE THREAD

**Issue by Enoch-X** [btiteam/xbtit#34]
Hello everybody,

After upgrade to XBTiT version 2.5.3, the comment function on torrents still don't work!
Inspection of the xbtit-root/comment.php file shows that the bug is not completely fixed!!!

on August 19 - 2016, the user q8-hma, gave the solution, 
[https://github.com/btiteam/xbtit/issues/11](url)
but no one updated the comment.php file that containes the script error, so I've fixed it myself and share it with the world.

There were two files that needed to be updated to fix the bug, namely: 

- xbtit-root/comment.php (in the root of the xbtit dir) 
- xbtit-root/style/xbtit_default/torrents.list.tpl (template file)

Now the torrents.list.tpl file is updated ( the error was a typo, **coments** needs to be **comments**!)
But the comment.php file in the XBTiT 2.5.3 version is not updated and still contains the error!!!

This is the answer and solution (by user q8-hma) to fix the bug:

update comment.php
find
`do_sqlquery("INSERT INTO {$TABLE_PREFIX}comments (added,text,ori_text,user,info_hash) VALUES (NOW(),\"$comment\",\"$comment\",\"$user\",\"" . mysqli_query($GLOBALS['conn'],StripSlashes($_POST["info_hash"])) . "\")",true);`

replace with
`do_sqlquery("INSERT INTO {$TABLE_PREFIX}comments (added,text,ori_text,user,info_hash) VALUES (NOW(),\"$comment\",\"$comment\",\"$user\",\"" . mysqli_real_escape_string($GLOBALS['conn'],StripSlashes($_POST["info_hash"])) . "\")",true);`

update torrents.list.tpl
find
`<td align="center" width="30" class="lista" style="text-align: center;"><tag:torrents[].coments /></td>`
replace with
`<td align="center" width="30" class="lista" style="text-align: center;"><tag:torrents[].comments /></td>`

That's all folks!
Greetz,
Bye!

**Comment by KingCobra58** [comment]
updated the comment.php file

**Comment by Enoch-X** [comment]
Okidoki!

Thanks! ;-)
