### ISSUE TITLE
PHP Deprecated warning

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#35]
may need to have a look as this for future php updates
PHP version
7.0.8-0ubuntu0.16.04.2
 PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; bTemplate has a deprecated constructor in bTemplate.php on line 8

i think changing this line 
function bTemplate($base_path = NULL, $reset_vars = TRUE) {
to
function __construct($base_path = NULL, $reset_vars = TRUE) {

may correct the warning

**Comment by Gh0st4unt3r** [comment]
For version 3 plus we are starting to look into the PHO and rewrite it using the YiiFramework along with a new template system such as smarty or twig.

let me know your thoughts on this and we will also look into this for version 2 currently.

**Comment by flier56** [comment]
i don't know much about YiiFramework but rewrites seem to go with upgrades

**Comment by KingCobra58** [comment]
@Gh0st4unt3r i have made a comment in the glitter Developers & said it needed to be checked in 2.5.3 it only gets this problem when php 7 is used
the fix i comment is from Lupin himself & was fixed for xbtitFM 2.1

**Comment by KingCobra58** [comment]
try this
in the class.ajaxpoll.php 
find this
`function poll`
replace with this
`function __construct`

in the class.captcha.php
find this
`function ocr_captcha
replace with
`function __construct`

**Comment by KingCobra58** [comment]
changing this line
function bTemplate($base_path = NULL, $reset_vars = TRUE) {
to
function  __construct($base_path = NULL, $reset_vars = TRUE) {
from what Lupin said you need that space between function & __construct
