### ISSUE TITLE
XBTiT downloads don't work on Android default browser and Chrome for Android

### ISSUE THREAD

**Issue by Enoch-X** [btiteam/xbtit#36]
Hi Everybody,

We've come to the conclusion that when you open the XBTiT webscript on an Android mobile device, the download creates an error and hangs as an incomplete error in the download queue.

This happens both on the default Android web browser as well as the Chrome for Android web browser, both products of Google inc. 

On the other hand, when we try the same downloads in a Firefox for Android web browser, everything works like a charm!!!

Testing downloads of torrent files on other web pages in the default Android web browser as well as the Chrome for Android web browser and it works without a problem!

Looks like Google don't like XBTiT, they're hostile towards it and they try to censurize it and block the download of XBTiT Torrent files in their webbrowsers. We have no other conclusion. Try and see for yourself.

We're looking for a workaround! All help is appreciated!

Greetings!

**Comment by jeanmarieclement** [comment]
Have you error in your apache error_log?

**Comment by imtiazmahbub** [comment]
I tried with both android stock browser and chrome for android. Didn't notice any problem.
