### ISSUE TITLE
Wrong ratio data sent to tracker rtorrent 0.9.6

### ISSUE THREAD

**Issue by byzon** [btiteam/xbtit#41]
Can you please look at this thread (Wrong ratio data sent to tracker) - rtorrent 0.9.6, libtorrent 0.13.6

https://github.com/rakshasa/rtorrent/issues/561

Some trackers have made a fix but they are based on tbdev

> I won't go into detail, but our tracker pre-supposed that peer_id was unique and tried to fetch the peer data from the database using only the peer_id. All we did was add another condition to the SQL statement: AND userid = $userid. The userid should already be present because it can be derived from the passkey."

**Comment by atmoner** [comment]
It looks like a strange one to an injection by the announce! I had this problem at the time ...
The torrent client sends a query to the annouce with the values set when the torrent is created. 
This query is formed by the client (here rtorrent) with the upload and download values on the url of the announce (rtorrent does not cheat!) So it is very likely that a software mimics a torrent client and sends Value much more important than the original values to bypass the ratio system.

I do not remember exactly, but I think there is a log system on xbtit, activates log history and monitors what happens!

**Comment by jeanmarieclement** [comment]
More info are needed: 
- php or xbtt backend?
- which version?
