### ISSUE TITLE
recover password - not passing rehash to db, xbtit 2.5.4

### ISSUE THREAD

**Issue by phempa** [btiteam/xbtit#43]
Greetings wonderful XBTIT dev team,

When resetting a password in v2.5.4, it appears that the rehashed password isn't being sent to the database. The following error flashes quickly after clicking the link in the email, before redirecting you to a success message:

**Warning:** mysqli_query(): Empty query in **/home/**_site_**/**_webroot_**/recover.php** on line **148**

This results in no hash in the **password** column for a particular user in the **xbtit_users** table, and the user is unable to log in.

The snippet of code at line 148 is the following:

do_sqlquery("UPDATE `{$TABLE_PREFIX}users` SET `password`='".mysqli_query($GLOBALS['conn'],$multipass[$i]["rehash"])."', `salt`='".mysqli_query($GLOBALS['conn'],$multipass[$i]["salt"])."', `pass_type`='".$i."', `dupe_hash`='".mysqli_query($GLOBALS['conn'],$multipass[$i]["dupehash"])."' WHERE `id`=$id AND  `random`=$random",true);

Install details are as follows:

Fully dedicated server
CentOS 6.8, WHM, cPanel
XBTIT 2.5.4 - fresh, unmodified installation
Apache 2.4
PHP 5.6
MySQL 5.0.11

Please let me know if you need more information to troubleshoot this issue.
Thanks for all your hard work on making XBTIT a great platform!

Ben@LL

**Comment by phempa** [comment]
Is there a way to receive some premium support for this bug? We need this resolved ASAP to continue our site, which has been on BTITracker code since 2005.

**Comment by jeanmarieclement** [comment]
Sorry, missed this issue, we will have a look ASAP ;)

**Comment by KingCobra58** [comment]
Try replacing this `mysqli_query($GLOBALS['conn']`
to this `mysqli_real_escape_string($GLOBALS['conn']`
in this query
`do_sqlquery("UPDATE {$TABLE_PREFIX}users SET password='".mysqli_query($GLOBALS['conn'],$multipass[$i]["rehash"])."', salt='".mysqli_query($GLOBALS['conn'],$multipass[$i]["salt"])."', pass_type='".$i."', dupe_hash='".mysqli_query($GLOBALS['conn'],$multipass[$i]["dupehash"])."' WHERE id=$id AND random=$random",true);`

**Comment by phempa** [comment]
Thank you KingCobra58, this resolved the issue!!!!

Password recovery function is working as intended, no errors at all.

Very much appreciated, we will be contributing to the XBTIT/DPWS Media team soon! Will contributions to the paypal@btiteam.org email be suitable?

**Comment by jeanmarieclement** [comment]
No, ask privately King Cobra ;)

**Comment by phempa** [comment]
Will do, thanks again!!!!

**Comment by phempa** [comment]
KingCobra, I'm having a hard time PM'ing you on the XBTIT forum - I keep failing the image validation.

Please send me an email at "phempa AT gmail DOT com" - I would like to donate to you and your team soon.

Thanks!

**Comment by KingCobra58** [comment]
@phempa
email sent mate
