### ISSUE TITLE
Password Hashing Method

### ISSUE THREAD

**Issue by HDVinnie** [btiteam/xbtit#47]
xbtit/include/functions.php

I am suggesting that this be a priority issue and that xbtit goes with the standard PHP bcrypt method and away from the outdated MD5.

**Comment by HDVinnie** [comment]
are devs going to acknowledge this issue?

**Comment by imtiazmahbub** [comment]
Yes, we will move away from MD5.
Any help on this would be greatly appreciated

**Comment by MarQuisKnox** [comment]
1. http://php.net/manual/en/function.password-hash.php
2. https://jonsuh.com/blog/securely-hash-passwords-with-php

**Comment by l3oncoder** [comment]
I have bcrypt password hashing on my install of xbtit, But however this break support for use with other forums software.
