### ISSUE TITLE
sql error when installing in 16.04 server

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#5]
in database.sql all date and time needs to change from '0000-00-00 00:00:00'
to '1000-01-01 00:00:00'
using 16.04
PHP version
7.0.4-7ubuntu2
MYSQL version
5.7.11-0ubuntu6

**Comment by Gh0st4unt3r** [comment]
Looking into this, test and will amend,

**Comment by Gh0st4unt3r** [comment]
Fix has been applied to master.
