### ISSUE TITLE
warning info peers.php

### ISSUE THREAD

**Issue by JUFEK** [btiteam/xbtit#51]
hello, peers.php tells me this
https://i.imgur.com/EugdYJZ.png

Warning: A non-numeric value encountered in /srv/www/dc-tracker.cz/www/include/common.php on line 644

Warning: A non-numeric value encountered in /srv/www/dc-tracker.cz/www/include/common.php on line 646

**Comment by imtiazmahbub** [comment]
can you please check if your peers table has any data? or if it gets updated with new data?

**Comment by JUFEK** [comment]
Yes table peers write correct data.
https://i.imgur.com/q7nU0ne.png
only warning above

**Comment by imtiazmahbub** [comment]
I mean the database table: `TABLE_PREFIX_peers`
