### ISSUE TITLE
a php warning need some help

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#52]
i have a  php warning showing up and need some help fixing it running xbtit 2.30 
including a copy of the file
[common.zip](https://github.com/btiteam/xbtit/files/1504370/common.zip)

PHP Warning:  mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /home/public/www/include/common.php on line 277
PHP Warning:  mysqli_free_result() expects parameter 1 to be mysqli_result, boolean given in /home/public/www/include/common.php on line 281

ubuntu 17.04 64
PHP version
7.0.22-0ubuntu0.17.04.1
mysql version
5.7.20-0ubuntu0.17.04.1

**Comment by KingCobra58** [comment]
that file isn't from the official xbtit it is from xbtit dt fm & we don't give support for that script here

**Comment by flier56** [comment]
i am not running xbtit dt fm i just modded some of hacks from it into the 2.30 script

**Comment by flier56** [comment]
thanks for your time any way i will get it figured out
