### ISSUE TITLE
Security perform

### ISSUE THREAD

**Issue by atmoner** [btiteam/xbtit#57]
Hello =) 
I think you should change the mode of operation to parser the variables!
The file crk_protection.php will never perform the right role knowing that xss evolves all the time (use of new tag etc ....)

Today, many variables are vulnerable to xss on xbtit! (as well as saying that all sites that use xbtit are affect)

crk_protection.php parse only a few tags! It should have the function of never letting the html tag pass

Simple exemple for internal forum search:

![xss](https://i.imgur.com/SSc6FFc.png)
 
And I post here the least dangerous!

**Comment by imtiazmahbub** [comment]
Hi atmoner! Seeing you after a very long time, my friend!

I don't know much about xss attacks. Do you think this will fix at least the svg attack?
```
$ban2=array('.....continued', '<svg');
```

**Comment by HDVinnie** [comment]
To prevent from XSS attacks, you just have to check and validate properly all user inputted data that you plan on using and dont allow html or javascript code to be inserted from that form.

Or you can you Use htmlspecialchars() to convert HTML characters into HTML entities. So characters like <> that mark the beginning/end of a tag are turned into html entities and you can use strip_tags() to only allow some tags as the function does not strip out harmful attributes like the onclick or onload.

However.....xbtit is decades old. Goes against so many PHP principles its not even funny. SOLID, DRY, the list goes on and on. I doubt anyone is every going to modernize it fully. It to messy and would take to much time and effort. Would be easier to build something new on a modern framework like Symphony, Laravel, etc.

**Comment by imtiazmahbub** [comment]
You're absolutely right, @HDVinnie . xbtit needs a complete rewrite. I'd like to see it come as a composer package with just the tracker essentials. Then anyone will be able to build over it on any framework.

**Comment by atmoner** [comment]
@imtiazmahbub o/
@HDVinnie You're totally right! I use a very simple function that I apply to each of my displays and it is very effective (several bugbounty pass without any problems)
```
function Fuckxss($var) {
		strip_tags($var);
		$output = htmlspecialchars($var, ENT_QUOTES);
	return $output;
}
```

I also confirm that xbtit is a dinosaur! (and I do not say that the wrong way but it's a reality).
In 2012, I had completely converted xbtit from Btemplate to Smarty
I managed to find the sources! https://sourceforge.net/projects/xbtit-smarty/
