### ISSUE TITLE
Remove uses of the PHP each function

### ISSUE THREAD

**Issue by HDVinnie** [btiteam/xbtit#62]
The function was deprecated in PHP 7.2 and we should look to replace the usage of it with a foreach loop.

**Comment by HDVinnie** [comment]
If interested in making codebase PHP 7.2 ready I can get this PR done. @imtiazmahbub

**Comment by imtiazmahbub** [comment]
That's a big help! Please go ahead @HDVinnie

**Comment by HDVinnie** [comment]
Cool I can do it and some more assuming my current PR gets merged. Then we can further work to make sure were using latest PHP standards and php 7.3 ready.
