### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#7]
install.php and upgrade.php missing from master

**Comment by Gh0st4unt3r** [comment]
just noticed i think my git updater has an error due to a recent update,  will get this amended asap.

**Comment by KingCobra58** [comment]
for now he can get them from here
https://github.com/btiteam/xbtit/tree/XBTIT-2.5.0

**Comment by flier56** [comment]
i have a copy just noticed they were missing thanks
