### ISSUE TITLE
 [Question] What is answer to the verification question of XBTIT Forum?

### ISSUE THREAD

**Issue by YellowHCH** [btiteam/xbtit#77]
### Issue Type
- [Question]

### Expected Behavior:
XBTIT Forum

### Actual Behavior:
You did not answer the verification questions correctly.

### Steps To Reproduce The Problem:
1.https://btiteam.eu
2.register
3.answer the verification question with "XBTIT Forum"

**Comment by KingCobra58** [comment]
I won't give the answer here in GitHub
You need to email me kingcobra@btiteam.eu

**Comment by KingCobra58** [comment]
This not an issue with the script
