### ISSUE TITLE
Blocks not showing

### ISSUE THREAD

**Issue by VENAXIS** [btiteam/xbtit#8]
The blocks are not showing on homepage.

**Comment by KingCobra58** [comment]
did you change the blocks permissions in the adminCP's block settings?

**Comment by VENAXIS** [comment]
Yes. Only the top and middle block sections work.

I just did a quick diagnostics test and noticed four image files are missing, could they be the reason for this? It looks like the files have the wrong urls:
```
/style/xbtit_default/css/images/ajaxchat/bubble.png
/style/xbtit_default/css/images/ajaxchat/loading.gif
/style/xbtit_default/css/images/ajaxchat/frame.png
/style/xbtit_default/css/images/titlebg.jpg
```

They should be inside the **xbtit_default** folder, which is why they are returning a 404 errors. Is it a problem from my end?

**Comment by Gh0st4unt3r** [comment]
the images should be fine as it will look from the directory where the index.php file is and with it being on root from there it will look in styles folder this is why the structure is like this.

on the older themes it would have been slightly different which will still work on the 2.5.0 without the bootstrap features.

check your folder and file permissions are readable chmod the files/folders 755 to double check.

let me know if this help on the issue.

**Comment by VENAXIS** [comment]
Folders are chmoded to 775. Sorry if this is a stupid question, but which folders/files exactly do I need to chmod?

Thanks for the answer.

**Comment by Gh0st4unt3r** [comment]
Try the style folders and files as it is related to the images and could you let us know what your www / public_html folder is aswell.

are you on a linux system, windows and we will try see if we can reproduce the error you are seeing also if you have a server error log can you post that aswell so we can pin point what the issue may be.

**Comment by VENAXIS** [comment]
I chmodded them but problem is still there. I'm using my own dedicated server running Centos 6.7 64-bit (VestaCP - Latest version).
It's installed on a sub-domain and using SSL. Problem still persists with SSL disabled.

I didn't have any of these problems with XBTIT 2.3, running on the same server with the same settings.

I have reinstalled it from scratch but still the same.

Here is the error log:
```
[Tue May 03 01:11:01 2016] [error] [client x.xx.xxx.xxx] File does not exist: /home/admin/web/sub.domain.com/public_html/style/xbtit_default/css/images, referer: http://sub.domain.com/style/xbtit_default/css/modern.css
[Tue May 03 01:13:37 2016] [error] [client x.xx.xxx.xxx] File does not exist: /home/admin/web/sub.domain.com/public_html/style/xbtit_default/css/images, referer: http://sub.domain.com/style/xbtit_default/css/modern.css
[Tue May 03 01:17:38 2016] [error] [client x.xx.xxx.xxx] File does not exist: /home/admin/web/sub.domain.com/public_html/style/xbtit_default/css/images, referer: http://sub.domain.com/style/xbtit_default/css/modern.css
[Tue May 03 01:29:29 2016] [error] [client x.xx.xxx.xxx] File does not exist: /home/admin/web/sub.domain.com/public_html/style/xbtit_default/css/images, referer: http://sub.domain.com/style/xbtit_default/css/modern.css
```

**Comment by Gh0st4unt3r** [comment]
Does the file exist in the locations it says, as the error seems to be saying the file does not exist, the path seems right and has all the files uploaded, if they have it is normally down to file or folder permissions that is causing the problems, either a folder up to the destination files are not readable/writable or something on your installation is blocking Apache getting to show them files.

I will do a bit of research to see what could be causing this for you. unless someone else has found a solution specific to you.

I see you mentioned you ran 2.3.0 before 2.5.0 have you done the upgrade to 2.4.0 before overwriting the 2.5.0 files ?

**Comment by VENAXIS** [comment]
Yes it does exist. I have changed the files/folders permissions but to no avail.

Thanks, I'll try different methods from my end to find a solution as well.

No, I did a clean installation for 2.5.0, no upgrades.

**Comment by VENAXIS** [comment]
I'm using a CDN network to pass all my traffic to it, since I'm only gonna use the HTTP announce URL. Where there any changes made after version 2.3 that could affect the domain being on the CDN's IP rather than the original server's address?

**Comment by Gh0st4unt3r** [comment]
the script uses a base url so the url you have specified it will use,  which has been tested on localhost and domain name, let me know how it works via ip and will try to make amendments where needed.

**Comment by thartley55** [comment]
Just to clarify what it looks like they have NOT said...
Right and Left blocks are not showing.
There is nothing wrong with the block(s)...if you change them to show in Center position...they are there.
So, somewhere, there is something telling script to NOT show Left and Right blocks.

**Comment by Gh0st4unt3r** [comment]
If its the left and right side blocks on the default theme we are working toward making it SEO and optimized with bootstrap, the left and right blocks can still be amended in the themes so that the blocks can show.

**Comment by thartley55** [comment]
Okay, so in other words...we are 'without side-blocks', until the next upgrade?
No big deal for me...as I have only setup the script to try out, before I decide to open a site with it.
I'll wait for the issue to be resolved.
Thanx

**Comment by Gh0st4unt3r** [comment]
You can still use side blocks so if you use a theme that allows side blocks it will work as we have left the code in as legacy code, this means that it enables anyone who wishes to have side blocks will work for designs that have the side block template code. we have not stopped the functionality in the core code so it is still usable in the templates.

just the main design we are working on is going to be fully optimized for bootstrap and gives the option for anyone who wants the side can still have them using a design that has the side blocks for the time being.

example tpl code for left column in main.tpl
<if:HAS_LEFT_COL>
    <tag:main_left />
 </if:HAS_LEFT_COL>

example tpl code for right column in main.tpl
<if:HAS_RIGHT_COL>
    <tag:main_right />
 </if:HAS_RIGHT_COL>

**Comment by HDVinnie** [comment]
fixed for next release of xbtit
