### ISSUE TITLE
online block

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#8]
Question
wondering if there was a fix for the online block no showing members correctly
thanks

**Comment by KingCobra58** [comment]
Thought it was fixed by changing session_id to session_name in the online_block.php

**Comment by flier56** [comment]
i am using 2.6.1 i do not see  session_id in the online_block.php i tried making that change i index.php
it did not fix it. i am running ubuntu16.04 5.6 php

**Comment by KingCobra58** [comment]
look in functions.php also

**Comment by flier56** [comment]
that did not fix it still just shows the name you are logged in under

**Comment by KingCobra58** [comment]
change all session_id('xbtit'); to session_name'xbtit');

**Comment by flier56** [comment]
i got it working now
in functions.php had to add
session_name('xbtit');
session_start(); in 2 places

**Comment by KingCobra58** [comment]
ok I will update it when I get time

**Comment by flier56** [comment]
thanks for your time

**Comment by flier56** [comment]
that fixed the online block but does not look to be the correct way to solve this problem no getting errors like this
PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /home/public/www/include/functions.php on line 483

**Comment by KingCobra58** [comment]
That warning is because the session code needs updating for either the new php versions or the MySQLi & haven't founf out the correct code for it yet

**Comment by KingCobra58** [comment]
If you have MySQL 5.7 try upgrading to MariaDB 5.5 but not any MariaDB 10.x versions xbtit has to be converted from MySQLI to PDO  for MariaDB 10.x versions

**Comment by flier56** [comment]
i have MySQL version 5.7.29 i might do some testing in virtualbox don't want to mess up my server

**Comment by flier56** [comment]
not seeing a easy way to install MariaDB 5.5 in ubuntu 16.04 wants to install MariaDB 10.1

**Comment by KingCobra58** [comment]
Sorry I only know CentOS 7 
maybe try MySQL 5.5 or 5.6

**Comment by flier56** [comment]
Thanks for your help and time, for now i am going to let it run like it is
