### ISSUE TITLE
wrong address

### ISSUE THREAD

**Issue by flier56** [btiteam/xbtit#9]
https://btiteam.eu looks to be pointing to the wrong address

**Comment by KingCobra58** [comment]
Have no clue why there is no subdomain in my OVH like that

**Comment by KingCobra58** [comment]
I have no redirects to that url either

**Comment by flier56** [comment]
i can reach the btiteam site with this url but some links do not work
https://btiteam.eu/index.php/

**Comment by KingCobra58** [comment]
Like what links

**Comment by flier56** [comment]
the hacks under recent downloads

**Comment by flier56** [comment]
this link https://btiteam.eu/ is redirected here https://forum.xbtit.eu/ a blank page

**Comment by KingCobra58** [comment]
I have no redirect setup anywhere to that url at all, so I don't know why it is doing that & the hacks downloads I will have to re-upload them since I changed control panels.
When I changed control panels I re-installed the os on the vps & re-installed all forums.

**Comment by KingCobra58** [comment]
Hack downloads is fixed now

**Comment by flier56** [comment]
downloads are working
https://btiteam.eu is still being redirected to  https://forum.xbtit.eu

**Comment by KingCobra58** [comment]
I sent a support ticket to OVH about it & still waiting for a reply

**Comment by flier56** [comment]
ok OVH may have to correct that

**Comment by KingCobra58** [comment]
Closing this now PM me with anything else about the forum & use GitHub for the script itself
